### ISSUE TITLE
about the codes of JKNet

### ISSUE THREAD

**Issue by zhangxiaowei5346** [DM2-ND/CFLP#1]
How can I use the encoder JKNet? I found the encoder was limited to GCN and GraphSage. thanks!

**Comment by zhao-tong** [comment]
It should be a bit higher than that, I think we had hits@20 of ~65 on Cora. Did you use the example command in the readme?

**Comment by zhangxiaowei5346** [comment]
yes, I just followed the readme commands on Cora，I can try again ，thanks！

Tong Zhao ***@***.***> 于2021年11月4日周四 上午10:26写道：
