### ISSUE TITLE
Function does not exist in scikit_network library：membership_matrix

### ISSUE THREAD

**Issue by xiaomi4356** [DM2-ND/CFLP#4]
Hello, I tried to cite your work and reproduce your code. But I met a serious problem.
You guys use the library ‘scikit_network’ in cf_utils.py, but I find this line of code reports an error:
from sknetwork.utils import membership_matrix.
The file ‘sknetwork.utils’ does not include the function ‘membership_matrix ’ at all.
I checked all the references for this library，and I did not find this function.
At the same time，there is a version error in requirements you offered.
pytorch = 1.6.0 is too old and is not available.
I hope you guys can provide a usable code.
Thank you again for your excellent work！

**Comment by zhao-tong** [comment]
Hi, thanks a lot for you interest in our work!
Regarding the `membership_metrix` function, I found that they changed its name to `get_membership`. More details can be found in [this PR](https://github.com/sknetwork-team/scikit-network/commit/ed22d4b38fce4c46e4da6d02e83ba6f1e905c46e). Can you try using the new name when running with a newer version of `scikit-network`?
Regarding how to install PyTorch 1.6.0, I would suggest you to follow the instructions provided by PyTorch [here](https://pytorch.org/get-started/previous-versions/#v160).
Hope these helps :)

**Comment by zhao-tong** [comment]
Closing this issue as there's no followup questions. Please feel free to open a new issue or re-open this one if you encounter other problems.
